# See additional params for local dev in docker-compose.override.yml
services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/trading_db
      - BINANCE_API_KEY
      - BINANCE_API_SECRET
      - BINANCE_TESTNET
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
