services:
  web:
    volumes:
      - .:/app
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/trading_db
    ports:
      - "${WEB_SERVICE_PORT:-5000}:80"

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${DB_SERVICE_PORT:-5432}:5432"
