services:
  web:
    build: .
    ports:
      - "${SERVER_PORT:-5000}:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/trading_db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading_db
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgres_data:
